name: Clean Test Case Compilation HW-2 C-2

on:
  push:
    paths:
      - 'test'
      
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        
    - name: Install Dependencies
      shell: bash
      run: |
        ./install-deps.sh
        
    - name: Compile Test Cases
      shell: bash
      run: |
        make -C test
